### ISSUE TITLE
Handling dashes in param name

### ISSUE THREAD

**Issue by altumano** [Microsoft/OpenAPI.NET.CSharpAnnotations#194]
If I have a comment in code like this:

`/// <param name="X-Correlation-Id" cref="string" in="header">`

then the XML generated by MSBuild is like this:

`<param name="X-Correlation-Id-Correlation-Id"`

And accordingly the JSON document generated by CSharpAnnotation also has wrong name of the parameter.
It happens whenever the parameter name has dashes.

I understand that this is a bug/feature of MSBuild, as it expects the parameter name to be a valid C# parameter name (no dashes). But HTTP headers may have dashes, and I need to document those.

Any workaround?

**Comment by altumano** [comment]
Found a workaround!

Instead of 
`/// <param name="X-Correlation-Id" cref="string" in="header">`
use
`/// <header name="X-Correlation-Id" cref="string">`

**Comment by Shwetap05** [comment]
This double dash issue is a known roslyn bug  and we have a issue tracked to workaround the issue https://github.com/Microsoft/OpenAPI.NET.CSharpAnnotations/issues/148. Since we already have a issue tracking this i will be closing this one. Feel free to reopen if you have more concerns regarding this.
