### ISSUE TITLE
Generic ASP.NET Core Controller(s) support?

### ISSUE THREAD

**Issue by mmisztal1980** [Microsoft/OpenAPI.NET.CSharpAnnotations#199]
Hi,
I was wondering if it would be possible to have OpenAPI support the generic controllers
https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.2 ?

**Comment by Shwetap05** [comment]
@mmisztal1980 i will investigate and get back to you on this.

**Comment by mmisztal1980** [comment]
Hi @Shwetap05 , any news on this feature?

**Comment by Shwetap05** [comment]
@mmisztal1980 sorry for the delay on getting back on this, upon reading on generic controllers, looks like it provides a way to discover types that should be treated as controllers upon run time and since our generation tooling is based upon visual studio documentation generated at compile time we will not be able to support it.
