### ISSUE TITLE
AdvancedConfigurationXmlDocument does not support param in path

### ISSUE THREAD

**Issue by srenrd** [microsoft/OpenAPI.NET.CSharpAnnotations#200]
My api has a path param that is needed for every single call. For this reason it seems like the configuration xml would be the perfect place to put this param.

When i try to add it in the configuration xml i get "Path paramater: [param name] is undocumented in http://someAddress/[param name]".

My xml:
```
<configuration>
  <operation>
    <annotation>
      <param name="[param name]" required="true" cref="T:System.String" in="path">description</param>
    </annotation>
  </operation>
</configuration>
```

Is this a bug or working as intended?

PS. Header and query params works just fine. Also the path param works when i place it in the summary for every single call. So it must be the configuration xml that does not support it.

**Comment by EricAtMSFT** [comment]
Hello @srenrd. I suspect we don't support path parameters due to their non standard location in the URI string. For example, what if a URI has two path params? How would you identify the location of each? Headers and querystring params can always be simple "appended" to the request, but path params must be put in a specific place in the URI. Let me follow up with some other contributors and we'll see if it's paractical to try to support this.

**Comment by EricAtMSFT** [comment]
Based on discussions and feedback, implementing this would be difficult and the scenario is likely uncommon. Closing unless we get wider interest.
