### ISSUE TITLE
When will the Project be released?

### ISSUE THREAD

**Issue by Flori00** [microsoft/OpenAPI.NET.CSharpAnnotations#212]
Hey,

i wanted to inform me if there is a new release date, because there weren't any releases yet, i saw that there was an released planned in January 2019, but nothing happend. Will there be an release? Is anyone working on this Project right now?

Thanks

**Comment by ChlorideCull** [comment]
>Is anyone working on this Project right now?

@Shwetap05 has been making commits as late as May this year, so I'd assume this project isn't dead.

**Comment by Shwetap05** [comment]
@Flori00 The project is very much alive and since i am the only developer working on it, issue fixes are some time delayed. Sorry for not updating the readme with correct release date, before releasing we are waiting on updating the Azure Dev Ops task with fix for #208. Will get back to you on new release date once discussed with the team and will update readme too.

**Comment by Flori00** [comment]
Thanks!
